### ISSUE TITLE
Where is your index.html file?

### ISSUE THREAD

**Issue by Ma1hT3ach3r** [SagnjeevieN/Game-Project#1]
If you don't have an index.html file then you will not be able to host your game.

You are hosting your javascript inside html.

**Comment by Kkoro1** [comment]
i'm working on it

**Comment by Ma1hT3ach3r** [comment]
Looks good!

**Comment by Ma1hT3ach3r** [comment]
Make sure you source the p5 libraries you use.
khanacademy makes use of the p5 library. (rectangles, image functions, etc.)
